import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {useRouterState, Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Header } from "@/components/Header";
import { SiteFooter } from "@/components/SiteFooter";
function NotFoundComponent(){return <main className="flex min-h-screen items-center justify-center bg-background px-6"><div className="max-w-lg text-center"><p className="font-display text-sm font-bold uppercase text-primary">404 / Wrong room</p><h1 className="mt-3 font-display text-5xl font-bold">That page needs fixing.</h1><p className="mt-4 text-muted-foreground">The page may have moved, but help is still close by.</p><Link to="/" className="mt-8 inline-flex min-h-11 items-center rounded-md bg-primary px-6 font-bold text-primary-foreground">Return to the repair house</Link></div></main>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"tanstack_root_error_component"}),[error]);return <main className="flex min-h-screen items-center justify-center px-6"><div className="text-center"><h1 className="font-display text-3xl font-bold">This page didn’t load.</h1><button className="mt-6 min-h-11 rounded-md bg-primary px-6 font-bold text-primary-foreground" onClick={()=>{router.invalidate();reset()}}>Try again</button></div></main>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1, viewport-fit=cover"},{name:"theme-color",content:"#0B1220"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();const home=useRouterState({select:(st)=>st.location.pathname})==="/";/* The homepage is one full-screen 3D environment: no page scroll, no footer. */return <QueryClientProvider client={queryClient}>{home?<div className="flex h-[100dvh] flex-col overflow-hidden overscroll-none"><Header/><Outlet/></div>:<div className="min-h-screen"><Header/><Outlet/><SiteFooter/></div>}</QueryClientProvider>}
