export type NeighborhoodZoneId = "west" | "core" | "east" | "yard";

export interface ProblemScene {
  id: string;
  label: string;
  symptom: string;
  serviceId: string;
  zone: NeighborhoodZoneId;
  position: [number, number, number];
  fix: string;
  urgent?: boolean;
}

export const neighborhoodZones = [
  { id: "west" as const, label: "Living & entry", center: [-5, 0, -1] as [number, number, number] },
  {
    id: "core" as const,
    label: "Kitchen & utilities",
    center: [0, 0, -2] as [number, number, number],
  },
  { id: "east" as const, label: "Bath & systems", center: [5, 0, -2] as [number, number, number] },
  {
    id: "yard" as const,
    label: "Exterior & smart home",
    center: [3, 0, 2] as [number, number, number],
  },
];

export const problemScenes: ProblemScene[] = [
  {
    id: "drywall-hole",
    label: "Drywall hole",
    symptom: "A damaged wall needs patching and paint blending.",
    serviceId: "handyman",
    zone: "west",
    position: [-6.8, 1.7, -5.65],
    fix: "Patch, sand, prime and color-match the wall.",
  },
  {
    id: "crooked-shelf",
    label: "Crooked shelf",
    symptom: "The shelf is loose and pulling away from the wall.",
    serviceId: "handyman",
    zone: "west",
    position: [-6.1, 2.4, -5.45],
    fix: "Reset anchors into solid framing and level the shelf.",
  },
  {
    id: "loose-door",
    label: "Loose door hinge",
    symptom: "The entry door rubs and will not close cleanly.",
    serviceId: "handyman",
    zone: "west",
    position: [-7.1, 1.3, -3.1],
    fix: "Re-seat the hinge, repair screw holes and align the latch.",
  },
  {
    id: "tv-mount",
    label: "TV mounting",
    symptom: "A television needs a safe, centered wall installation.",
    serviceId: "handyman",
    zone: "west",
    position: [-5.2, 2.2, -4.8],
    fix: "Locate studs, install the rated mount and conceal cables.",
  },
  {
    id: "dead-outlet",
    label: "Dead outlet",
    symptom: "An outlet has stopped supplying power.",
    serviceId: "electrical",
    zone: "core",
    position: [-3.3, 1, -5.65],
    fix: "Test the circuit and replace or reconnect the failed device.",
    urgent: true,
  },
  {
    id: "flickering-pendant",
    label: "Flickering pendant",
    symptom: "The kitchen light flickers intermittently.",
    serviceId: "electrical",
    zone: "core",
    position: [-2.1, 3.1, -4.8],
    fix: "Inspect the fixture, connections, switch and circuit load.",
  },
  {
    id: "tripping-breaker",
    label: "Tripping breaker",
    symptom: "A breaker trips when several devices run.",
    serviceId: "electrical",
    zone: "core",
    position: [-1.1, 1.7, -5.65],
    fix: "Diagnose the load and correct the licensed electrical fault.",
    urgent: true,
  },
  {
    id: "smoke-detector",
    label: "Detector warning",
    symptom: "A smoke detector is chirping and overdue for service.",
    serviceId: "electrical",
    zone: "core",
    position: [-0.3, 3.7, -5.65],
    fix: "Replace the battery or expired detector and test the circuit.",
  },
  {
    id: "dripping-faucet",
    label: "Dripping faucet",
    symptom: "A faucet continues dripping after it is shut off.",
    serviceId: "plumbing",
    zone: "core",
    position: [1.3, 1.35, -4.5],
    fix: "Replace the worn cartridge or seals and test for leaks.",
  },
  {
    id: "leaking-pipe",
    label: "Leaking pipe",
    symptom: "Water is collecting below the kitchen sink.",
    serviceId: "plumbing",
    zone: "core",
    position: [2.1, 0.55, -4.7],
    fix: "Isolate the supply and repair the failed joint or line.",
    urgent: true,
  },
  {
    id: "running-toilet",
    label: "Running toilet",
    symptom: "The toilet continues running after every flush.",
    serviceId: "plumbing",
    zone: "east",
    position: [3.7, 1, -4.9],
    fix: "Replace the worn fill or flush components and tune the level.",
  },
  {
    id: "slow-drain",
    label: "Slow drain",
    symptom: "The shower drain is backing up during use.",
    serviceId: "plumbing",
    zone: "east",
    position: [4.7, 0.45, -4.6],
    fix: "Clear the obstruction and inspect the drain line.",
  },
  {
    id: "water-heater",
    label: "Cold water",
    symptom: "The water heater is no longer producing reliable hot water.",
    serviceId: "plumbing",
    zone: "east",
    position: [5.6, 1.35, -4.8],
    fix: "Diagnose the controls, elements or burner and repair safely.",
  },
  {
    id: "warm-air",
    label: "AC blowing warm",
    symptom: "The system runs, but the home is not cooling.",
    serviceId: "hvac",
    zone: "east",
    position: [6.4, 1.2, -3.4],
    fix: "Check airflow, refrigerant-side symptoms and equipment operation.",
    urgent: true,
  },
  {
    id: "thermostat",
    label: "Thermostat offline",
    symptom: "The thermostat display is blank and unresponsive.",
    serviceId: "hvac",
    zone: "east",
    position: [7, 2.2, -5.55],
    fix: "Restore control power or replace and configure the thermostat.",
  },
  {
    id: "blocked-vent",
    label: "Weak airflow",
    symptom: "One room receives very little conditioned air.",
    serviceId: "hvac",
    zone: "east",
    position: [5.5, 0.25, -2.5],
    fix: "Inspect the register, duct path, filter and system balance.",
  },
  {
    id: "fridge-warm",
    label: "Warm refrigerator",
    symptom: "Fresh food is no longer staying cold.",
    serviceId: "appliances",
    zone: "west",
    position: [-6.7, 1.6, 0.9],
    fix: "Diagnose airflow, controls, seals and the cooling system.",
  },
  {
    id: "washer-error",
    label: "Washer error",
    symptom: "The washer stops mid-cycle with an error code.",
    serviceId: "appliances",
    zone: "west",
    position: [-5.5, 1.2, 1.9],
    fix: "Read the fault, inspect drainage and repair the failed part.",
  },
  {
    id: "dryer-no-heat",
    label: "Dryer has no heat",
    symptom: "The drum turns but clothing stays damp.",
    serviceId: "appliances",
    zone: "west",
    position: [-4.4, 1.2, 1.9],
    fix: "Test airflow, thermal protection and the heating system.",
  },
  {
    id: "dishwasher-leak",
    label: "Dishwasher leak",
    symptom: "Water appears at the front of the dishwasher.",
    serviceId: "appliances",
    zone: "core",
    position: [-3, 1, 1.7],
    fix: "Inspect the seal, inlet, drain and leveling.",
  },
  {
    id: "cabinet-hinge",
    label: "Broken cabinet hinge",
    symptom: "A cabinet door sags and will not stay aligned.",
    serviceId: "interior",
    zone: "core",
    position: [-1.8, 1.4, 1.9],
    fix: "Repair the mounting points and install a matched hinge.",
  },
  {
    id: "cracked-tile",
    label: "Cracked tile",
    symptom: "A floor tile is cracked near a high-traffic edge.",
    serviceId: "interior",
    zone: "core",
    position: [-0.5, 0.15, 2.2],
    fix: "Remove the damaged tile, reset the substrate and regrout.",
  },
  {
    id: "roof-leak",
    label: "Roof leak",
    symptom: "A ceiling stain suggests water is entering above.",
    serviceId: "exterior",
    zone: "yard",
    position: [2.5, 3.4, 1.7],
    fix: "Trace the entry point and repair shingles or flashing.",
    urgent: true,
  },
  {
    id: "loose-gutter",
    label: "Loose gutter",
    symptom: "A gutter section is pulling away from the fascia.",
    serviceId: "exterior",
    zone: "yard",
    position: [3.7, 2.4, 2.2],
    fix: "Repair the fascia connection, reset pitch and secure hangers.",
  },
  {
    id: "gate-dragging",
    label: "Dragging gate",
    symptom: "The yard gate drags and no longer latches.",
    serviceId: "exterior",
    zone: "yard",
    position: [4.8, 1, 2.6],
    fix: "Square the frame, reinforce hinges and align the latch.",
  },
  {
    id: "doorbell-offline",
    label: "Doorbell offline",
    symptom: "The video doorbell will not connect or ring.",
    serviceId: "smart",
    zone: "yard",
    position: [6.3, 1.55, 1.7],
    fix: "Restore power and network setup, then test alerts.",
  },
];

export const getProblem = (id?: string | null) =>
  problemScenes.find((problem) => problem.id === id);
