import type { ServiceCategory } from "@/types";
export const excludedServicesNote = "Regular house cleaning, junk removal, lawn mowing, pressure washing, tree care and general property cleanup are handled by KleanupCrew.com.";
export const services: ServiceCategory[] = [
 { id:"handyman", name:"Handyman & Installations", shortName:"Handyman", description:"Everyday repairs, mounting, assembly and finishing work handled with care.", licensedProvider:false, accent:"amber", icon:"Hammer", services:["General handyman repairs","TV, shelf, mirror & wall mounting","Furniture assembly","Doors, windows & locks","Drywall, painting & carpentry","Accessibility & child-safety installation"] },
 { id:"electrical", name:"Electrical & Lighting", shortName:"Electrical", description:"Troubleshooting and safe electrical work by appropriately qualified or licensed providers.", licensedProvider:true, accent:"yellow", icon:"Zap", services:["Electrical troubleshooting","Outlets, switches & lighting","Ceiling fans","Breakers, panels & circuits","EV chargers","Generators"] },
 { id:"plumbing", name:"Plumbing & Water", shortName:"Plumbing", description:"Water-system troubleshooting and repairs by appropriately qualified or licensed plumbing providers.", licensedProvider:true, accent:"cyan", icon:"Droplets", services:["Leaks, faucets & sinks","Toilets & drains","Showers, tubs & disposals","Water-pressure problems","Water heaters","Sewer & septic specialists"] },
 { id:"hvac", name:"Heating & Air", shortName:"Heating & Air", description:"Comfort-system diagnosis, repair and maintenance by appropriately qualified or licensed HVAC providers.", licensedProvider:true, accent:"sky", icon:"Wind", services:["Heating & air conditioning","Thermostats & furnaces","Heat pumps & mini-splits","Ductwork & airflow","Indoor air quality","Preventive HVAC maintenance"] },
 { id:"appliances", name:"Appliance Repair", shortName:"Appliances", description:"Diagnosis, repair and installation for the appliances your property relies on.", licensedProvider:false, accent:"rose", icon:"Refrigerator", services:["Refrigerators","Washers & dryers","Dishwashers","Ovens & ranges","Microwaves","Appliance installation"] },
 { id:"interior", name:"Interior Repairs", shortName:"Interior", description:"Restore interior surfaces, cabinetry, flooring and finish details.", licensedProvider:false, accent:"violet", icon:"PaintRoller", services:["Drywall & painting","Cabinets & countertops","Tile & grout","Flooring","Baseboards & molding","Railings & carpentry"] },
 { id:"exterior", name:"Exterior & Structural Repairs", shortName:"Exterior", description:"Protect and restore the systems that form the exterior of your property.", licensedProvider:true, accent:"emerald", icon:"House", services:["Roofing & shingles","Siding, soffit & fascia","Gutters & downspouts","Decks, porches & fences","Concrete & masonry","Garage doors & sheds"] },
 { id:"smart", name:"Smart Home & Specialty", shortName:"Smart Home", description:"Connected-home equipment, safety sensors and specialized property upgrades.", licensedProvider:false, accent:"lime", icon:"RadioTower", services:["Doorbells & cameras","Smart locks & sensors","Smoke & CO detectors","Leak detection","Accessibility modifications","Solar & home-energy controls"] },
];
export const getService = (id?: string | null) => services.find((service) => service.id === id);
